.. note::
    Controller-0 and controller-1 use IP multicast messaging for
    synchronization. If loss of synchronization occurs a few minutes after
    controller-1 becomes available, ensure that the switches and other devices
    on the management and infrastructure networks are configured with
    appropriate settings.

    In particular, if |IGMP| snooping is enabled on |ToR| switches, then a
    device acting as an |IGMP| querier is required on the network (on the same
    |VLAN|) to prevent nodes from being dropped from the multicast group. The
    |IGMP| querier periodically sends |IGMP| queries to all nodes on the
    network, and each node sends an |IGMP| join or report in response. Without
    an |IGMP| querier, the nodes do not periodically send |IGMP| join messages
    after the initial join sent when the link first goes up, and they are
    eventually dropped from the multicast group.
