.. table:: Table 1. Common OpenStack Labels
    :widths: auto

    +-----------------------------+---------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
    | Label                       | Worker/Controller         | Description                                                                                                                                                                              |
    +=============================+===========================+==========================================================================================================================================================================================+
    | **openstack-control-plane** | -   Controller            | Identifies a node to deploy openstack controller services on.                                                                                                                            |
    |                             |                           |                                                                                                                                                                                          |
    |                             | -   All-in-One Controller |                                                                                                                                                                                          |
    +-----------------------------+---------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
    | **openstack-compute-node**  | Worker                    | Identifies a node to deploy openstack compute agents on.                                                                                                                                 |
    |                             |                           |                                                                                                                                                                                          |
    |                             |                           | .. note::                                                                                                                                                                                |
    |                             |                           |     Adding or removing this label, or removing a node with this label from a cluster, triggers the regeneration and application of the helm chart override of the OpenStack application. |
    +-----------------------------+---------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
    | **sriov**                   | -   Worker                | Identifies a node as supporting sr-iov.                                                                                                                                                  |
    |                             |                           |                                                                                                                                                                                          |
    |                             | -   All-in-One Controller |                                                                                                                                                                                          |
    +-----------------------------+---------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
