.. figures_begin

.. figure:: /configuration/figures/stx_proxy_overview.png
   :width: 500
   :alt: |prod| proxy usage

   Figure 1: |prod| proxy usage

.. figures_end

.. r3_begin

----------------------
Set proxy at bootstrap
----------------------

To set the Docker proxy at bootstrap time, refer to :ref:`Ansible Bootstrap
Configurations
<ansible_bootstrap_configs_r7>`.

.. r3_end

