
.. deployment-scenario-begin
.. deployment-scenario-end

.. code-block:: none

    system_mode: duplex
    distributed_cloud_role: systemcontroller


    management_start_address: <X.Y.Z>.2
    management_end_address: <X.Y.Z>.50



    additional_local_registry_images:
        - quay.io/external_storage/rbd-provisioner:v2.1.1-k8s1.11
        - docker.io/starlingx/ceph-config-helper:ubuntu_bionic-20220802
