
.. deployment-scenario-begin
.. deployment-scenario-end

.. parsed-literal::

    system_mode: duplex
    distributed_cloud_role: systemcontroller


    management_start_address: <X.Y.Z>.2
    management_end_address: <X.Y.Z>.50



    additional_local_registry_images:
        - quay.io/external_storage/rbd-provisioner:|v_external_storage-rbd-provisioner|
        - docker.io/openstackhelm/ceph-config-helper:|v_openstackhelm-ceph-config-helper|
