-   To remove labels from the host, do the following.

    .. code-block:: none

        ~(keystone)admin)$ system host-label-remove compute-0 openstack-compute-node sriov
        Deleted host label openstack-compute-node for host compute-0
        Deleted host label SRIOV for host compute-0

-   To assign Kubernetes labels to identify compute-0 as a compute node with
    |SRIOV|, use the following command:

    .. code-block:: none

        ~(keystone)admin)$ system host-label-assign compute-0 openstack-compute-node=enabled sriov=enabled
        +-------------+--------------------------------------+
        | Property    | Value                                |
        +-------------+--------------------------------------+
        | uuid        | 2909d775-cd6c-4bc1-8268-27499fe38d5e |
        | host_uuid   | 1f00d8a4-f520-41ee-b608-1b50054b1cd8 |
        | label_key   | openstack-compute-node               |
        | label_value | enabled                              |
        +-------------+--------------------------------------+
        +-------------+--------------------------------------+
        | Property    | Value                                |
        +-------------+--------------------------------------+
        | uuid        | d8e29e62-4173-4445-886c-9a95b0d6fee1 |
        | host_uuid   | 1f00d8a4-f520-41ee-b608-1b50054b1cd8 |
        | label_key   | SRIOV                                |
        | label_value | enabled                              |
        +-------------+--------------------------------------+

