
.. rsg1586183719424
.. _alarm-messages-overview:

Alarm messages are numerically coded by the type of alarm.

For more information, see
:ref:`Fault Management Overview <fault-management-overview>`.

In the alarm description tables, the severity of the alarms is represented by
one or more letters, as follows:

.. _alarm-messages-overview-ul-jsd-jkg-vp:

-   C: Critical

    Indicates that a platform service affecting condition has occurred and immediate
    corrective action is required. (A mandatory platform service has become totally
    out of service and its capability must be restored.)

-   M: Major

    Indicates that a platform service affecting condition has developed and urgent
    corrective action is required. (A mandatory platform service has developed a severe
    degradation and its full capability must be restored.)

    - or -

    An optional platform service has become totally out of service and its capability
    should be restored.


-   m: Minor

    Indicates that a platform non-service affecting fault condition has developed and
    corrective action should be taken in order to prevent a more serious fault. (The
    fault condition is not currently impacting / degrading the capability of the platform
    service.)

-   W: Warning

    Indicates the detection of a potential or impending service affecting fault. Action
    should be taken to further diagnose and correct the problem in order to prevent it
    from becoming a more serious service affecting fault

A slash-separated list of letters is used when the alarm can be triggered with
one of several severity levels.

An asterisk \(\*\) indicates the management-affecting severity, if any. A
management-affecting alarm is one that cannot be ignored at the indicated
severity level or higher by using relaxed alarm rules during an orchestrated
patch or upgrade operation.

.. note::
    **Degrade Affecting Severity: Critical** indicates a node will be
    degraded if the alarm reaches a Critical level.