.. include:: /shared/_includes/uline.rest

:command:`software` is the command-line interface for the |VIM| Orchestration
APIs.

This page documents the :command:`software` command.

For a full description of usage and optional arguments for a specific
:command:`software` command, enter:

.. code-block::

   ~(keystone_admin)]$ software <command> -h
