The Customer Logs include events that do not require immediate user action.

The following types of events are included in the Customer Logs. The severity
of the events can be one of:

* Critical

* Major

* Minor

* Warning

* NA (Not applicable)


